# themeNoPipe: true

title:
titleEn:
description:
images:

license:
  title_of_work: This website
  link_to_work: $URL
  createor_of_work: $NAME
  link_to_creator_profile: $URL
  year_of_creation: $YEAR

featuredImages:
  - image1.png
  - image2.jpg

googleFonts:
  - https://fonts.googleapis.com/css2?family=Gothic+A1:wght@300;700&display=swap
