title: Just bootstraped blog

languageCode: ko-kr
defaultContentLanguage: ko
hasCJKLanguage: true

disableKinds:
  - taxonomy
  - term

build:
  writeStats: true

googleAnalytics:

themesDir: ../..
theme: hugo-theme-bs
