hugoVersion:
  extended: true
  min: "0.91.2"

imports:
- path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5
- path: github.com/mozodev/hugo-theme-bs
replacements: "github.com/mozodev/hugo-theme-bs -> ../.."
